## Objective
### Forecasting Google Trends Using VAR and SARIMA Models
- Introduction: 
This project analyzes the relationship between Bitcoin search interest and the term "Crypto Crash" using Google Trends data. 

- The goal is to understand whether changes in one search trend can help predict movements in the other, so this project applies time series forecasting techniques such as VAR and SARIMA models.

The Project includes: 
- collect and analyze Google Trends data using the pytrends library.
- checking stationarity and integration order of the time series.
- performing Granger causality tests.
- buiding VAR and SARIMA forecasting models.
- generating out-of-sample forecasts.
- comparing model performance using RMSE and MAE metrics.

- The results will help determine whether multivariate (VAR) or univariate (SARIMA) models better capture and predict Google search behavior in the cryptocurrency market.

### Import Libraries

In [14]:
!pip install pytrends

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pytrends.request import TrendReq
from statsmodels.tsa.stattools import adfuller, grangercausalitytests
from statsmodels.tsa.api import VAR
from statsmodels.tsa.statespace.sarimax import SARIMAX

from sklearn.metrics import mean_squared_error, mean_absolute_error

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pytrends in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (4.9.2)
Requirement already satisfied: requests>=2.0 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytrends) (2.32.5)
Requirement already satisfied: pandas>=0.25 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytrends) (3.0.1)
Requirement already satisfied: lxml in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pytrends) (6.1.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.25->pytrends) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.25->pytrends) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=0.25->pytrends) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=0.25->pytrends) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.0->pytrends) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.0->pytrends) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.0->pytrends) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\getde\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.0->pytrends) (2026.2.25)

## Data Loading

In [16]:
from pytrends.request import TrendReq

pytrends = TrendReq()

kw_list = ["Bitcoin", "Crypto crash"]

pytrends.build_payload(kw_list,
                       timeframe='2021-01-01 2026-01-01',
                       geo='')

data = pytrends.interest_over_time()
data = data.drop(columns=['isPartial'])

# Save CSV 
data.to_csv("bitcoin_crypto_trends.csv", index=True)

data.head()

            Bitcoin  Crypto crash
date
2020-12-27       52             0
2021-01-03       86             0
2021-01-10       83             0
2021-01-17       53             0
2021-01-24       50             0

### Data Interpretation
- The dataset was collected using the pytrends library, which provides Google Trends data representing relative search interest over time. The analysis includes two keywords: “Bitcoin” and “Crypto crash”, covering the period from 2021 to 2026 at a global level.
- The values range between 0 and 100, where 100 represents the peak popularity of a search term within the selected timeframe. From the preview of the dataset, it can be observed that the “Bitcoin” series shows relatively continuous variation over time, reflecting general interest in the cryptocurrency market.
- The “Crypto crash” series contains many zero values with occasional spikes, indicating that searches related to market crashes occur irregularly and are concentrated around specific events. This suggests that “Crypto crash” captures sudden panic or crisis-driven behavior rather than consistent search activity.
- Additionally, the dataset is indexed by time and appears to follow a weekly frequency, which is typical for Google Trends data over long time horizons.

In [17]:
print(data.index[:10])
print(data.index.to_series().diff().value_counts())

DatetimeIndex(['2020-12-27', '2021-01-03', '2021-01-10', '2021-01-17',
               '2021-01-24', '2021-01-31', '2021-02-07', '2021-02-14',
               '2021-02-21', '2021-02-28'],
              dtype='datetime64[s]', name='date', freq=None)
date
7 days    261
Name: count, dtype: int64

## Initial Inspection

In [19]:
data = pd.read_csv("bitcoin_crypto_trends.csv", index_col=0, parse_dates=True)
data.head()

            Bitcoin  Crypto crash
date
2020-12-27       52             0
2021-01-03       86             0
2021-01-10       83             0
2021-01-17       53             0
2021-01-24       50             0

### Data Loading and Initial Inspection
The dataset was successfully loaded from the saved CSV file. The preview confirms that both variables are present and correctly indexed by date. This ensures the data is ready for further analysis.

## Stationary Test (Augmented Dickey-Fuller Test)

In [20]:
from statsmodels.tsa.stattools import adfuller

for col in data.columns:
    result = adfuller(data[col])
    print(f"Results for {col}")
    print("ADF Statistic:", result[0])
    print("p-value:", result[1])
    print("----------------------")

Results for Bitcoin
ADF Statistic: -3.3406774826131818
p-value: 0.01315525866691327
----------------------
Results for Crypto crash
ADF Statistic: -6.0025995800449214
p-value: 1.643783188431306e-07
----------------------

### Stationarity Test (Augmented Dickey-Fuller Test):

#### Hypothesis:
- null hypothesis (H₀): The time series is non-stationary (has a unit root).
- Alternative hypothesis (H₁): The time series is stationary.

#### Result and Interpretation:
- The Augmented Dickey-Fuller (ADF) test results indicate that both “Bitcoin” and “Crypto crash” series are stationary, as their p-values are below the 0.05 significance level.
- In particular, the p-value for “crypto crash” is extremely close to zero, which provides strong statistical evidence against the presence of a unit root. This confirms that the series is highly stationary.
- Therefore, the null hypothesis of non-stationarity is rejected for both variables, and the original series can be directly used for further analysis without applying differencing.

### Verification

In [21]:
print(data.columns)

Index(['Bitcoin', 'Crypto crash'], dtype='str')

In [22]:
print(data.info())

<class 'pandas.DataFrame'>
DatetimeIndex: 262 entries, 2020-12-27 to 2025-12-28
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Bitcoin       262 non-null    int64
 1   Crypto crash  262 non-null    int64
dtypes: int64(2)
memory usage: 6.1 KB
None

### Data Structure Verification
- The structure of the dataset was verified using the info() function. The output confirms that the date variable is correctly set as a DateTime index, which ensures that it is treated as a time reference rather than a variable in the analysis.
- The dataset contains two numerical variables, “Bitcoin” and “Crypto crash”, both of which have complete observations with no missing values and that means The data types are appropriate for time series analysis.
- This confirms that the dataset is properly formatted and suitable for applying statistical tests such as the Augmented Dickey-Fuller (ADF) test and further modeling techniques.

## Granger Causality Test
### Hypotheses
**Test 1: Bitcoin → Crypto crash**
- H₀: The first variable does NOT Granger-cause the second variable.
- H₁: The first variable DOES Granger-cause the second variable.
**Test 2: Crypto crash → Bitcoin**
- H₀: “crypto crash” does not Granger-cause Bitcoin
- H₁: “crypto crash” Granger-causes Bitcoin

In [23]:
from statsmodels.tsa.stattools import grangercausalitytests

grangercausalitytests(data[['Bitcoin', 'Crypto crash']], maxlag=5)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=5.5809  , p=0.0189  , df_denom=258, df_num=1
ssr based chi2 test:   chi2=5.6458  , p=0.0175  , df=1
likelihood ratio test: chi2=5.5856  , p=0.0181  , df=1
parameter F test:         F=5.5809  , p=0.0189  , df_denom=258, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=3.4890  , p=0.0320  , df_denom=255, df_num=2
ssr based chi2 test:   chi2=7.1147  , p=0.0285  , df=2
likelihood ratio test: chi2=7.0191  , p=0.0299  , df=2
parameter F test:         F=3.4890  , p=0.0320  , df_denom=255, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.3856  , p=0.2477  , df_denom=252, df_num=3
ssr based chi2 test:   chi2=4.2721  , p=0.2335  , df=3
likelihood ratio test: chi2=4.2373  , p=0.2370  , df=3
parameter F test:         F=1.3856  , p=0.2477  , df_denom=252, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.9229  , p=0.0218  , df_denom=249, df_num=4
ssr based chi2 test:   chi2=12.1141 , p=0.0165  , df=4
likelihood ratio test: chi2=11.8383 , p=0.0186  , df=4
parameter F test:         F=2.9229  , p=0.0218  , df_denom=249, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=4.7075  , p=0.0004  , df_denom=246, df_num=5
ssr based chi2 test:   chi2=24.5898 , p=0.0002  , df=5
likelihood ratio test: chi2=23.4835 , p=0.0003  , df=5
parameter F test:         F=4.7075  , p=0.0004  , df_denom=246, df_num=5

{np.int64(1): ({'ssr_ftest': (np.float64(5.580911602862954),
    np.float64(0.01890009537385209),
    np.float64(258.0),
    np.int64(1)),
   'ssr_chi2test': (np.float64(5.645805923826476),
    np.float64(0.017497172168369542),
    np.int64(1)),
   'lrtest': (np.float64(5.585609017026854),
    np.float64(0.018108635489356883),
    np.int64(1)),
   'params_ftest': (np.float64(5.580911602863031),
    np.float64(0.01890009537385126),
    np.float64(258.0),
    1.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e7e30>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e62d0>,
   array([[0., 1., 0.]])]),
 np.int64(2): ({'ssr_ftest': (np.float64(3.4889624277784046),
    np.float64(0.03199808908714054),
    np.float64(255.0),
    np.int64(2)),
   'ssr_chi2test': (np.float64(7.114746911548118),
    np.float64(0.028513618726922586),
    np.int64(2)),
   'lrtest': (np.float64(7.019141681866813),
    np.float64(0.029909747722383532),
    np.int64(2)),
   'params_ftest': (np.float64(3.488962427778436),
    np.float64(0.03199808908713956),
    np.float64(255.0),
    2.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e6f90>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e6d50>,
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 np.int64(3): ({'ssr_ftest': (np.float64(1.3855556003628997),
    np.float64(0.24767045993977366),
    np.float64(252.0),
    np.int64(3)),
   'ssr_chi2test': (np.float64(4.272129767785608),
    np.float64(0.23353881521892317),
    np.int64(3)),
   'lrtest': (np.float64(4.237278714461354),
    np.float64(0.2369559804883919),
    np.int64(3)),
   'params_ftest': (np.float64(1.3855556003628733),
    np.float64(0.24767045993978176),
    np.float64(252.0),
    3.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e4e30>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e4bf0>,
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])]),
 np.int64(4): ({'ssr_ftest': (np.float64(2.922889364698281),
    np.float64(0.021750797345655815),
    np.float64(249.0),
    np.int64(4)),
   'ssr_chi2test': (np.float64(12.114143872966372),
    np.float64(0.0165223427022258),
    np.int64(4)),
   'lrtest': (np.float64(11.838340275124665),
    np.float64(0.018594781587453212),
    np.int64(4)),
   'params_ftest': (np.float64(2.922889364698273),
    np.float64(0.0217507973456561),
    np.float64(249.0),
    4.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e5310>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e5670>,
   array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]),
 np.int64(5): ({'ssr_ftest': (np.float64(4.707467895916935),
    np.float64(0.0004000039375338118),
    np.float64(246.0),
    np.int64(5)),
   'ssr_chi2test': (np.float64(24.589822139240898),
    np.float64(0.00016717825257603577),
    np.int64(5)),
   'lrtest': (np.float64(23.48347671136048),
    np.float64(0.00027278053777742055),
    np.int64(5)),
   'params_ftest': (np.float64(4.707467895916944),
    np.float64(0.0004000039375338033),
    np.float64(246.0),
    5.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e5c10>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e65d0>,
   array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}

### Interpretation of Granger Causality Test:
#### Test 1:
- The Granger Causality Test was conducted to determine whether Bitcoin can predict Crypto Crash events.
- The null hypothesis states that Bitcoin does not Granger-cause Crypto Crash. 
- The results indicate statistically significant causality at lag lengths 1, 2, 4, and 5, the p-values obtained from the SSR-based F-test, Chi-square test, Likelihood Ratio test, and Parameter F-test are all below the 5% significance level. Therefore, the null hypothesis is rejected for these lags. This indicates that past Bitcoin values contain statistically significant information that helps predict future Crypto Crash movements.
- However, for lag 3, the p-values exceed 0.05, so the null hypothesis cannot be rejected at that lag. Overall, the evidence suggests the existence of Granger causality from Bitcoin to Crypto Crash, particularly at lag lengths 1, 2, 4, and 5.

## Reverse Causality

In [24]:
grangercausalitytests(data[['Crypto crash', 'Bitcoin']], maxlag=5)

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0749  , p=0.7846  , df_denom=258, df_num=1
ssr based chi2 test:   chi2=0.0757  , p=0.7832  , df=1
likelihood ratio test: chi2=0.0757  , p=0.7832  , df=1
parameter F test:         F=0.0749  , p=0.7846  , df_denom=258, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0336  , p=0.9670  , df_denom=255, df_num=2
ssr based chi2 test:   chi2=0.0685  , p=0.9663  , df=2
likelihood ratio test: chi2=0.0685  , p=0.9663  , df=2
parameter F test:         F=0.0336  , p=0.9670  , df_denom=255, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0788  , p=0.9714  , df_denom=252, df_num=3
ssr based chi2 test:   chi2=0.2430  , p=0.9704  , df=3
likelihood ratio test: chi2=0.2429  , p=0.9704  , df=3
parameter F test:         F=0.0788  , p=0.9714  , df_denom=252, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8001  , p=0.5261  , df_denom=249, df_num=4
ssr based chi2 test:   chi2=3.3161  , p=0.5064  , df=4
likelihood ratio test: chi2=3.2950  , p=0.5097  , df=4
parameter F test:         F=0.8001  , p=0.5261  , df_denom=249, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.5746  , p=0.7194  , df_denom=246, df_num=5
ssr based chi2 test:   chi2=3.0017  , p=0.6997  , df=5
likelihood ratio test: chi2=2.9843  , p=0.7024  , df=5
parameter F test:         F=0.5746  , p=0.7194  , df_denom=246, df_num=5

{np.int64(1): ({'ssr_ftest': (np.float64(0.07486886496648108),
    np.float64(0.7845942334129135),
    np.float64(258.0),
    np.int64(1)),
   'ssr_chi2test': (np.float64(0.07573943316376575),
    np.float64(0.783156455187072),
    np.int64(1)),
   'lrtest': (np.float64(0.07572844589913075),
    np.float64(0.783171791076221),
    np.int64(1)),
   'params_ftest': (np.float64(0.07486886496646197),
    np.float64(0.7845942334129404),
    np.float64(258.0),
    1.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d025e5a90>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d026002f0>,
   array([[0., 1., 0.]])]),
 np.int64(2): ({'ssr_ftest': (np.float64(0.033591633718451745),
    np.float64(0.9669705786244722),
    np.float64(255.0),
    np.int64(2)),
   'ssr_chi2test': (np.float64(0.06850058640625455),
    np.float64(0.9663296086332851),
    np.int64(2)),
   'lrtest': (np.float64(0.06849156427892922),
    np.float64(0.966333967817501),
    np.int64(2)),
   'params_ftest': (np.float64(0.03359163371846096),
    np.float64(0.9669705786244633),
    np.float64(255.0),
    2.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02600c50>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02600b30>,
   array([[0., 0., 1., 0., 0.],
          [0., 0., 0., 1., 0.]])]),
 np.int64(3): ({'ssr_ftest': (np.float64(0.07880939739756958),
    np.float64(0.9714431497074855),
    np.float64(252.0),
    np.int64(3)),
   'ssr_chi2test': (np.float64(0.2429956419758395),
    np.float64(0.9703668642236722),
    np.int64(3)),
   'lrtest': (np.float64(0.24288172310366463),
    np.float64(0.9703867023482164),
    np.int64(3)),
   'params_ftest': (np.float64(0.07880939739759216),
    np.float64(0.9714431497074738),
    np.float64(252.0),
    3.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02601550>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02601430>,
   array([[0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0.]])]),
 np.int64(4): ({'ssr_ftest': (np.float64(0.8001132220778107),
    np.float64(0.5260960186714232),
    np.float64(249.0),
    np.int64(4)),
   'ssr_chi2test': (np.float64(3.3161319083706853),
    np.float64(0.5063803659427248),
    np.int64(4)),
   'lrtest': (np.float64(3.295001286305933),
    np.float64(0.5097246496395909),
    np.int64(4)),
   'params_ftest': (np.float64(0.8001132220778261),
    np.float64(0.5260960186714134),
    np.float64(249.0),
    4.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02601e50>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02601d30>,
   array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]),
 np.int64(5): ({'ssr_ftest': (np.float64(0.5746369161650545),
    np.float64(0.7194199385973763),
    np.float64(246.0),
    np.int64(5)),
   'ssr_chi2test': (np.float64(3.0016603141142078),
    np.float64(0.6997298481205174),
    np.int64(5)),
   'lrtest': (np.float64(2.9842665043227043),
    np.float64(0.7024116147071109),
    np.int64(5)),
   'params_ftest': (np.float64(0.5746369161650106),
    np.float64(0.7194199385974098),
    np.float64(246.0),
    5.0)},
  [<statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02602750>,
   <statsmodels.regression.linear_model.RegressionResultsWrapper at 0x19d02602630>,
   array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}

### Interpretation of Reverse Causality Test
- A reverse Granger Causality Test was conducted to examine whether Crypto Crash events can predict Bitcoin movements.
-  The null hypothesis states that Crypto Crash does not Granger-cause Bitcoin. The results show that the p-values for all lag lengths (1–5) are greater than the 5% significance level.
- Therefore, the null hypothesis cannot be rejected. This indicates that past Crypto Crash values do not provide statistically significant information for predicting future Bitcoin movements.
- There is no evidence of Granger causality running from Crypto Crash to Bitcoin.